/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *  
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *  
 *    http://www.apache.org/licenses/LICENSE-2.0
 *  
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.wirez.basicset.client;

import com.google.gwt.safehtml.shared.SafeUri;
import org.wirez.basicset.api.BasicSet;
import org.wirez.basicset.client.resources.BasicSetmageResources;
import org.wirez.core.api.DefinitionManager;
import org.wirez.core.client.AbstractBindableShapeSet;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;

// TODO: Should be generated by annot processors.

@ApplicationScoped
public class BasicShapeSet extends AbstractBindableShapeSet {

    public static final String ID = "BasicShapeSet";

    @Inject
    public BasicShapeSet( final DefinitionManager definitionManager ) {
        super( definitionManager );
    }

    @Override
    public String getId() {
        return ID;
    }

    @Override
    public SafeUri getThumbnailUri() {
        return BasicSetmageResources.INSTANCE.basicSetThumb().getSafeUri();
    }

    @Override
    protected Class<?> getDefinitionSetClass() {
        return BasicSet.class;
    }

}
